export const WRITE_SUCCESS = "WRITE_TO_ASYNC_STORAGE_SUCCESS";
export const WRITE_FAILED  = "WRITE_TO_ASYNC_STORAGE_FAILED";

export const READ_SUCCESS  = "READ_FROM_ASYNC_STORAGE_SUCCESS";
export const READ_FAILED   = "READ_FROM_ASYNC_STORAGE_FAILED";